[project]
name = "pandemic-common"
version = "0.0.1"
description = "Common utilities and types for Pandemic system"
readme = "README.md"
license = {text = "MIT"}
keywords = ["edge", "common", "types"]
authors = [{name = "Pandemic Team"}]
dependencies = [
    "pydantic>=2.0",
    "pyyaml>=6.0"
]

[project.optional-dependencies]
test = ["pytest>=7.0", "pytest-cov>=4.0"]
dev = ["black>=23.0", "isort>=5.0", "mypy>=1.0", "flake8>=6.0"]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"