[project]
name = "pandemic-console"
version = "0.0.1"
description = "Web-based dashboard for Pandemic edge computing system"
readme = "README.md"
license = {text = "MIT"}
keywords = ["web", "dashboard", "ui", "react", "typescript"]
authors = [{name = "Pandemic Team"}]
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "pyyaml>=6.0",
    "pandemic-common==0.0.1"
]

[project.optional-dependencies]
test = ["pytest>=7.0", "pytest-asyncio>=0.21", "pytest-cov>=4.0", "httpx>=0.25.0"]
dev = ["black>=23.0", "isort>=5.0", "mypy>=1.0", "flake8>=6.0"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
pandemic_console = ["console/**/*"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"