[project]
name = "pandemic-event-bus"
version = "0.0.1"
description = "Event bus infection plugin for pandemic system"
readme = "README.md"
license = {text = "MIT"}
keywords = ["event", "bus", "daemon", "infection"]
authors = [{name = "Pandemic Team"}]
dependencies = [
    "pandemic-common==0.0.1"
]

[project.optional-dependencies]
test = ["pytest>=7.0", "pytest-asyncio>=0.26", "pytest-cov>=4.0"]
dev = ["black>=23.0", "isort>=5.0", "mypy>=1.0", "flake8>=6.0"]

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project.scripts]
pandemic-event-daemon = "pandemic_event_bus.__main__:main"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "-v --tb=short"
asyncio_mode = "auto"