name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip build twine
        make install-dev

    - name: Build frontend
      run: |
        cd packages/pandemic-console
        ./build.sh

    - name: Build packages
      run: |
        python -m build packages/pandemic-common
        python -m build packages/pandemic-core
        python -m build packages/pandemic-cli
        python -m build packages/pandemic-iam
        python -m build packages/pandemic-rest
        python -m build packages/pandemic-console

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: packages/*/dist/*
        generate_release_notes: true
        draft: false
        prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload packages/*/dist/* --skip-existing